### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by olliefr** [valocode/bubbly#105]
Docusaurus configuration includes a Discord invite link which is not valid.

After having had a quick glance at the [Bubbly documentation website](https://docs.bubbly.dev/), I cannot see this information being publicly available, but maybe it's just me.

https://github.com/valocode/bubbly/blob/0a9ff9b9ebcf2bb7b57072d7c91e7af5a802421a/docs/docusaurus.config.js#L61

![image](https://user-images.githubusercontent.com/967105/117043110-7a238a00-ad15-11eb-9390-5d3eeebc1700.png)

## Proposed solution

Either fix the Discord link or remove it from Docusaurus configuration :shipit:

**Comment by maitesin** [comment]
As far as I remember, the discord invite links are only valid for 7 days. I do not know if you can create a link that never expires.
