### ISSUE TITLE
Dependencies: upgrade to NATS server `v2`

### ISSUE THREAD

**Issue by olliefr** [valocode/bubbly#11]
This is a more speculative request. 

We depend on `v1` of NATS server, which has some well-documented `go.mod`-related shenanigans [1].

[1] [NATS v2 & Go Modules (github.com)](https://gist.github.com/wallyqs/7dfe08e6833b2075b5a947bb986949ab)

## Proposed resolution

- [ ] Upgrade to `github.com/nats-io/nats-server/v2`. 

To this end, I was able to run all our tests successfully after running a single command from [1] to replace all imports of `v1` with `v2`. But I have little experience with NATS server, so I am deferring this decision to @benmarsden.

**Comment by nate-droid** [comment]
If this seems to be a relatively easy fix, I would vote that this gets bumped up in priority. Reason being that the older NATs version has several vulnerabilities found:
[1](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMNATSIONATSSERVERSERVER-1037609)
[2](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMNATSIONATSSERVERSERVER-1042967)

**Comment by olliefr** [comment]
@benmarsden I'm happy to bump up the version of NATS ASAP and submit a PR, but that would mean you'd have to rebase your changes on the latest `main` straight after. Shall we do that? Ping me on Slack, if that's OK. I'm open to alternative approaches as well.

**Comment by benmarsden** [comment]
> @benmarsden I'm happy to bump up the version of NATS ASAP and submit a PR, but that would mean you'd have to rebase your changes on the latest `main` straight after. Shall we do that? Ping me on Slack, if that's OK. I'm open to alternative approaches as well.

Do it!
