### ISSUE TITLE
Docker Container Security and Best Practices

### ISSUE THREAD

**Issue by nate-droid** [valocode/bubbly#2]
We need to update our docker images to use best practices and scan for security vulns.

Inspiration:
https://sysdig.com/blog/dockerfile-best-practices/

**Comment by olliefr** [comment]
From our friendly colleagues, we got recommendations for the following tools:

* Exploring image size issues: [`dive`](https://github.com/wagoodman/dive) 
* Image security scanner: [`anchore`](https://anchore.com/)
