### ISSUE TITLE
Remove "v1" from Bubbly Files

### ISSUE THREAD

**Issue by nate-droid** [valocode/bubbly#52]
Since we are only using 1 version of the API at the moment, having "v1" in the Bubbly files, just adds extra lines of code. We will default to using v1.

**Comment by jlarfors** [comment]
Here are the docs: https://pkg.go.dev/github.com/hashicorp/hcl/v2/gohcl

So we should add the `hcl:"api_verison,optional"` for the hcl tag.
Then remove the `api_version` from examples so that it doesn't keep getting copied around
