### ISSUE TITLE
`apiResponse` is not used by anything except swagger docs

### ISSUE THREAD

**Issue by jlarfors** [valocode/bubbly#53]
All the swagger comments mark the return as `apiResponse` yet it isn't actually used by anything...

E.g. 

```golang
// Query godoc
// @Summary Query performs graphql related tasks
...
// @Success 200 {object} apiResponse
// @Failure 400 {object} apiResponse
...
func (s *Server) Query(c echo.Context) error {
```

We are now using echo's `HTTPError` as the return on an error:

```golang
        HTTPError struct {
		Code     int         `json:"-"`
		Message  interface{} `json:"message"`
		Internal error       `json:"-"` // Stores the error returned by an external dependency
	}
```

On success, we don't have a common return type, or do we?

**Comment by olliefr** [comment]
As I have conjectured in PR #113, the Swagger docs most likely are out-of-date. I had an intent to create an issue for updating them, but then I came across this. After I had fixed close to two dozens of small issues in that PR, the `apiResponse` is the _only_ linter warning that we have. Whoever is going to close this ticket with a PR is cordially invited to review Swagger docs and update them as well as figuring out what to do with `apiResponse` in a way that would make the linter happy 🙃 

There is also a question I was going to ask as to why are we not providing a Swagger end-point for interactive exploration of the API? Swagger has support for `echo`, which is the router that we are using, so I think it would be a good idea? Especially, considering the fact that we are investing time updating Swagger documentation. Might as well add that interactivity to Bubbly :shipit: 🚀
