### ISSUE TITLE
Implement the `limit` argument to the root types in GraphQL

### ISSUE THREAD

**Issue by olliefr** [valocode/bubbly#90]
We would like to be able to limit the number of items, returned by the top-level GraphQL query, such as

```graphql
my_outstanding_personal_qualities(limit: 5) {
  name
  worth_in_gold
}
```

❗ Note, that this feature is limited only to the root types, just as the `order_by` and `distinct_on` currently are. 

So, the following won't work:

```graphql
my_outstanding_personal_qualities(limit: 5) {

  name
  worth_in_gold

  rich_and_beautiful_friends_they_bring(limit: 50) {
    name
    telephone_number
    net_wealth
  }
}
```

The inner limit (value `50`) would produce an error. This is due to the way our SQL queries are being built.

**Comment by olliefr** [comment]
There is support for the `limit` argument in `graphql.go` but at the moment it does not result in any changes to the actual SQL query in `postgres_graphql.go`. Thus, the "front end" is there, but the "back end" is not (yet).

This issue is concerned with the implementation of the "back end" and the associated tests.

**Comment by jlarfors** [comment]
Is it not possible to have this in nested fields, or is it just more complicated?

If we are asking for only x amount of something in a nested field... now this only allows us to return x SQL rows overall, right?
I can't think of an exact use case right now for nested limit, but it feels like it's going to be useful

**Comment by olliefr** [comment]
I, too, think this would have been very useful! 

It certainly _can_ be done, but it would be a task much larger in scope. The current implementation uses simple `JOIN` statements between the tables that form the hierarchy. If you'd like to `LIMIT` the output of any of the child tables, that implies building a subquery for every child table and _then_ joining the results of the subqueries.

Now that I think of it, even at the top level adding the limit is non-trivial because you cannot just use `LIMIT` in your top-level SQL clause - the results table would have multiple entries because we are collapsing an object hierarchy into a single table. That old issue again. This limitation means that `limit` probably has to be implemented with a clever use of `WHERE` or, Codd forbid, ranking functions and a sliding window 😂 

Perhaps, we could rethink the whole approach and try resolving inner types first as subqueries, joining the results later. That would solve this problem (and a handful of others), but again, that would be a task much bigger in scope.

Not that I'm against it, obviously :shipit:

**Comment by olliefr** [comment]
I mean, I'd be the first one to want to place a `limit` on the total number of rich and beautiful friends that I have! 🙄
